before:
  hooks:
    - go mod download
builds:
  - main: main.go
    binary: boring-registry
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s
      - -w
      - -X github.com/boring-registry/boring-registry/version.Version={{.Version}}
      - -X github.com/boring-registry/boring-registry/version.Commit={{.Commit}}
      - -X github.com/boring-registry/boring-registry/version.Date={{.Date}}
      - -X github.com/boring-registry/boring-registry/version.BuiltBy=goreleaser
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
