{{- if .Values.server.route.enabled -}}
{{- $fullName := include "boring-registry.fullname" . -}}
apiVersion: {{ .Values.server.route.apiVersion }}
kind: {{ .Values.server.route.kind }}
metadata:
  name: {{ $fullName }}
  namespace: {{ include "boring-registry.namespace" . }}
  labels:
    {{- include "boring-registry.labels" . | nindent 4 }}
    {{- with .Values.server.route.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.server.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- with .Values.server.route.parentRefs }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  hostnames:
    {{- range $hostname := $.Values.server.route.hostnames }}
    - {{ $hostname }}
    {{- end }}
  rules:
    {{- range $rule := .Values.server.route.rules }}
    - backendRefs:
        - kind: Service
          name: {{ $fullName }}
          port: {{ $.Values.server.service.port }}
      {{- with $rule.matches }}
      matches:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $rule.filters }}
      filters:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $rule.sessionPersistence }}
      sessionPersistence:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $rule.timeouts }}
      timeouts:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $rule.retry }}
      retry:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }}
