{{- if .Values.server.auth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "boring-registry.fullname" . }}
  labels:
    {{- include "boring-registry.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.server.auth.value }}
  apiKey: {{ .Values.server.auth.value | b64enc }}
  {{- else }}
  apiKey: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end }}
