{
 "title": "boring-registry overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS by HTTP Method",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{container=\"boring-registry\"}[$__rate_interval])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS by HTTP Status Code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{container=\"boring-registry\"}[$__rate_interval])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "timeseries",
   "description": "Responses with 4xx status code are discarded from the calculation",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{container=\"boring-registry\", code=~\"[2].*\"}[$__rate_interval])) / sum(rate(http_request_duration_seconds_count{container=\"boring-registry\", code=~\"[^4].*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (le)(\n    rate(\n        http_request_duration_seconds_bucket{container=\"boring-registry\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (le)(\n    rate(\n        http_request_duration_seconds_bucket{container=\"boring-registry\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le)(\n    rate(\n        http_request_duration_seconds_bucket{container=\"boring-registry\"}[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Client Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{container=\"boring-registry\", code=~\"4..\"}[$__rate_interval])) by (code, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Modules", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Module list version operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(boring_registry_modules_list_versions_total[$__rate_interval])) by (namespace, provider, name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Module download operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(boring_registry_modules_download_version_total[$__rate_interval])) by (namespace, provider, name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 module list versions",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "topk(5, sum(increase(boring_registry_modules_list_versions_total[$__range])) by(name, namespace, provider))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 module downloads",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "topk(5, sum(increase(boring_registry_modules_download_version_total[$__range])) by(name, namespace, provider))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Providers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Provider list version operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(boring_registry_providers_list_versions_total[$__rate_interval])) by (namespace, provider, name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Provider download operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(boring_registry_providers_download_version_total[$__rate_interval])) by (namespace, provider, name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 provider list versions",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "topk(5, sum(increase(boring_registry_providers_list_versions_total[$__range])) by(name, namespace, provider))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 provider downloads",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "topk(5, sum(increase(boring_registry_providers_download_version_total[$__range])) by(name, namespace, provider))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Provider Mirror", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Provider Mirror list versions operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(boring_registry_mirrors_list_provider_versions_total[$__rate_interval])) by (hostname, namespace, name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Provider Mirror list versions operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(boring_registry_mirrors_list_provider_versions_total[$__rate_interval])) by (hostname, namespace, name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Provider Mirror download operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(boring_registry_mirrors_download_version_total[$__rate_interval])) by (hostname, namespace, name)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}